spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    url: 'jdbc:postgresql://localhost:5432/school_app'
    username: postgres
    password: postgres
    driver-class-name: 'org.postgresql.Driver'